version: "3"

services:
  app:
    image: hub.teko.vn/identity/admin/api:develop
    build: .
    ports:
      - 5000:5000
    restart: on-failure
    volumes: 
      - .:/app
      - ./logs:/app/app/logs
    command: ["flask", "run", "--host=0.0.0.0", "--port=5000"]