"""empty message

Revision ID: 34b8ff83c959
Revises: e0c039511839
Create Date: 2020-02-25 01:00:13.150978

"""
from alembic import op
import sqlalchemy as sa
from app.models.base import GUID
from sqlalchemy.dialects import mysql
import uuid

# revision identifiers, used by Alembic.
revision = '34b8ff83c959'
down_revision = 'e0c039511839'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('templates',
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('active', sa.Boolean(), nullable=True),
                    sa.Column('id', GUID(), default=uuid.uuid4, nullable=False),
                    sa.Column('name', sa.String(length=255), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    op.create_table('domains',
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('active', sa.Boolean(), nullable=True),
                    sa.Column('id', GUID(), default=uuid.uuid4, nullable=False),
                    sa.Column('user_id', GUID(), default=uuid.uuid4, nullable=True),
                    sa.Column('url', sa.String(length=100), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('url')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('domains')
    op.drop_table('templates')
    # ### end Alembic commands ###
