"""empty message

Revision ID: 57a1cc0b820d
Revises: 9334bf50426c
Create Date: 2019-12-28 23:12:06.628435

"""
from alembic import op
import sqlalchemy as sa
from app.models.base import GUID
from sqlalchemy.dialects import mysql
import uuid

# revision identifiers, used by Alembic.
revision = '57a1cc0b820d'
down_revision = '9334bf50426c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers', sa.Column('adv_id', GUID(), default=uuid.uuid4, nullable=True))
    op.create_foreign_key(None, 'offers', 'advs', ['adv_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'offers', type_='foreignkey')
    op.drop_column('offers', 'adv_id')
    # ### end Alembic commands ###
