"""empty message

Revision ID: 70bcc98b040e
Revises: 5388bcfe66b6
Create Date: 2020-03-03 22:39:55.295429

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '70bcc98b040e'
down_revision = '5388bcfe66b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('postback_logs', 'order_id',
                    existing_type=mysql.INTEGER(display_width=11),
                    type_=sa.String(length=255),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('postback_logs', 'order_id',
                    existing_type=sa.String(length=255),
                    type_=mysql.INTEGER(display_width=11),
                    nullable=True)
    # ### end Alembic commands ###
