"""empty message

Revision ID: 9334bf50426c
Revises: 20657171323e
Create Date: 2019-12-19 12:15:41.102364

"""
from alembic import op
import sqlalchemy as sa
from app.models.base import GUID
from sqlalchemy.dialects import mysql
import uuid

# revision identifiers, used by Alembic.
revision = '9334bf50426c'
down_revision = '20657171323e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advs',
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('active', sa.Boolean(), nullable=True),
                    sa.Column('id', GUID(), default=uuid.uuid4, nullable=False),
                    sa.Column('username', sa.String(length=100), nullable=False),
                    sa.Column('email', sa.String(length=120), nullable=True),
                    sa.Column('fullname', sa.String(length=100), nullable=True),
                    sa.Column('password_hash', sa.String(length=255), nullable=True),
                    sa.Column('meta_data', sa.JSON(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email'),
                    sa.UniqueConstraint('username')
                    )
    op.create_table('categories',
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('active', sa.Boolean(), nullable=True),
                    sa.Column('id', GUID(), default=uuid.uuid4, nullable=False),
                    sa.Column('name', sa.String(length=100), nullable=False),
                    sa.Column('description', sa.Text(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    op.create_table('roles',
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('active', sa.Boolean(), nullable=True),
                    sa.Column('id', GUID(), default=uuid.uuid4, nullable=False),
                    sa.Column('name', sa.String(length=255), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    op.create_table('offers',
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('active', sa.Boolean(), nullable=True),
                    sa.Column('id', GUID(), default=uuid.uuid4, nullable=False),
                    sa.Column('alias', sa.String(length=20), nullable=False),
                    sa.Column('name', sa.String(length=100), nullable=False),
                    sa.Column('geo', sa.String(length=20), nullable=True),
                    sa.Column('img', sa.Text(), nullable=True),
                    sa.Column('category_id', GUID(), nullable=True),
                    sa.Column('description', sa.Text(), nullable=True),
                    sa.Column('short_desc', sa.Text(), nullable=True),
                    sa.Column('country_code', sa.String(length=20), nullable=True),
                    sa.Column('payout_share', sa.Float(), nullable=True),
                    sa.Column('ecpc', sa.Float(), nullable=True),
                    sa.Column('price', sa.Float(), nullable=True),
                    sa.Column('meta_data', sa.JSON(), nullable=True),
                    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('alias')
                    )
    op.drop_index('name', table_name='role')
    op.drop_table('role')
    op.alter_column('users', 'active',
                    existing_type=mysql.TINYINT(display_width=1),
                    type_=sa.Boolean(),
                    existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'active',
                    existing_type=sa.Boolean(),
                    type_=mysql.TINYINT(display_width=1),
                    existing_nullable=True)
    op.create_table('role',
                    sa.Column('created_at', mysql.DATETIME(), nullable=True),
                    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
                    sa.Column('active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
                    sa.Column('id', mysql.CHAR(collation='utf8mb4_general_ci', length=32), nullable=False),
                    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    mysql_collate='utf8mb4_general_ci',
                    mysql_default_charset='utf8mb4',
                    mysql_engine='InnoDB'
                    )
    op.create_index('name', 'role', ['name'], unique=True)
    op.drop_table('offers')
    op.drop_table('roles')
    op.drop_table('categories')
    op.drop_table('advs')
    # ### end Alembic commands ###
