"""empty message

Revision ID: bd5bb861b06b
Revises: 34b8ff83c959
Create Date: 2020-02-25 22:42:16.937644

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'bd5bb861b06b'
down_revision = '34b8ff83c959'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('postback_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'postback_url')
    # ### end Alembic commands ###
