"""empty message

Revision ID: e0c039511839
Revises: 57a1cc0b820d
Create Date: 2020-01-05 15:28:48.584826

"""
from alembic import op
import sqlalchemy as sa
from app.models.base import GUID
import uuid

# revision identifiers, used by Alembic.
revision = 'e0c039511839'
down_revision = '57a1cc0b820d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversions',
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('active', sa.Boolean(), nullable=True),
                    sa.Column('order_id', sa.Integer(), nullable=False),
                    sa.Column('id', GUID(), default=uuid.uuid4, nullable=True),
                    sa.Column('publisher_name', sa.String(length=255), nullable=False),
                    sa.Column('user_id', GUID(), default=uuid.uuid4, nullable=True),
                    sa.Column('phone', sa.String(length=20), nullable=False),
                    sa.Column('name', sa.String(length=100), nullable=False),
                    sa.Column('address', sa.String(length=100), nullable=True),
                    sa.Column('external_id', sa.String(length=100), nullable=True),
                    sa.Column('offer_id', GUID(), default=uuid.uuid4, nullable=True),
                    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'DUPLICATED', 'TRASHED', name='conversionstatus'), nullable=True),
                    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('order_id'),
                    sa.UniqueConstraint('external_id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conversions')
    # ### end Alembic commands ###
